package org.esupportail.ects

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._
import io.gatling.core.session.Expression

class EchelleNotEctsEtp extends Simulation {

	val httpProtocol = http
		.baseURL("http://localhost:8080")
		.acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8")
		.acceptEncodingHeader("gzip,deflate,sdch")
		.acceptLanguageHeader("fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4")
		.connection("keep-alive")
		.doNotTrackHeader("1")
		.userAgentHeader("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/33.0.1750.152 Chrome/33.0.1750.152 Safari/537.36")

	val headers = Map(
		"""Accept""" -> """text/css,*/*;q=0.1""",
		"""If-Modified-Since""" -> """Fri, 18 Apr 2014 06:47:33 GMT""")

	val headers2 = Map(
		"""Content-Type""" -> """application/x-www-form-urlencoded""",
		"""Faces-Request""" -> """partial/ajax""",
		"""Origin""" -> """http://localhost:8080""",
		"""X-Requested-With""" -> """XMLHttpRequest""")

  val headers3 = Map("""Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8""")

  val jsfViewStateCheck = regex("""="javax.faces.ViewState" value="([^"]*)"""")
    .saveAs("viewState")
  def jsfGet(name: String, url: Expression[String]) = http(name).get(url)
    .check(jsfViewStateCheck)
  def jsfPost(name: String, url: Expression[String]) = http(name).post(url)
    .param("javax.faces.ViewState", "${viewState}")
    .check(jsfViewStateCheck)

	val echelleNotEctsEtp = scenario("echelleNotEctsEtp")
		.exec(http("accueil_1")
			.get("""/"""))
		.pause(79 milliseconds)
		.exec(http("accueil_2")
			.get("""/javax.faces.resource/jsf.js.xhtml?ln=javax.faces"""))
		.pause(18 milliseconds)
		.exec(http("accueil_3")
			.get("""/javax.faces.resource/growl/assets/growl.css.xhtml?ln=primefaces"""))
		.exec(http("accueil_4")
			.get("""/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces"""))
		.pause(14 milliseconds)
		.exec(http("accueil_5")
			.get("""/javax.faces.resource/core/core.js.xhtml?ln=primefaces"""))
		.exec(http("accueil_6")
			.get("""/javax.faces.resource/growl/growl.js.xhtml?ln=primefaces"""))
		.exec(http("accueil_7")
			.get("""/javax.faces.resource/jquery/ui/jquery-ui.css.xhtml?ln=primefaces"""))
		.exec(http("accueil_8")
			.get("""/javax.faces.resource/wijmo/wijmo.css.xhtml?ln=primefaces"""))
		.exec(http("accueil_9")
			.get("""/javax.faces.resource/panel/panel.css.xhtml?ln=primefaces"""))
		.exec(http("accueil_10")
			.get("""/javax.faces.resource/jquery/ui/jquery-ui.js.xhtml?ln=primefaces"""))
		.pause(16 milliseconds)
		.exec(http("accueil_11")
			.get("""/javax.faces.resource/wijmo/wijmo.js.xhtml?ln=primefaces"""))
		.exec(http("accueil_12")
			.get("""/javax.faces.resource/panel/panel.js.xhtml?ln=primefaces"""))
		.exec(http("accueil_13")
			.get("""/javax.faces.resource/button/button.js.xhtml?ln=primefaces"""))
		.exec(http("accueil_14")
			.get("""/javax.faces.resource/ajaxstatus/ajaxstatus.js.xhtml?ln=primefaces"""))
		.exec(http("accueil_15")
			.get("""/javax.faces.resource/paginator/paginator.css.xhtml?ln=primefaces"""))
		.exec(http("accueil_16")
			.get("""/javax.faces.resource/datatable/datatable.css.xhtml?ln=primefaces"""))
		.exec(http("accueil_17")
			.get("""/javax.faces.resource/yui/utilities/utilities.js.xhtml?ln=primefaces"""))
		.pause(11 milliseconds)
		.exec(http("accueil_18")
			.get("""/javax.faces.resource/paginator/paginator.js.xhtml?ln=primefaces"""))
		.exec(http("accueil_19")
			.get("""/javax.faces.resource/datatable/datatable.js.xhtml?ln=primefaces"""))
		.exec(http("accueil_20")
			.get("""/javax.faces.resource/themes/sam/theme.css.xhtml?ln=primefaces"""))
		.exec(http("accueil_21")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/rennes1.css"""))
		.exec(http("accueil_22")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.fss.css"""))
		.exec(http("accueil_23")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.reset.css"""))
		.exec(http("accueil_24")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.layout.css"""))
		.exec(http("accueil_25")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.text.css"""))
		.exec(http("accueil_26")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/application.layout.css"""))
		.exec(http("accueil_27")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.reset.css"""))
		.exec(http("accueil_28")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.theme.css"""))
		.exec(http("accueil_29")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.layout.css"""))
		.exec(http("accueil_30")
			.get("""/media//style/ects.css""")
			.headers(headers))
		.pause(15 milliseconds)
		.exec(http("accueil_31")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/logo-header.png"""))
		.exec(http("accueil_32")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/background_logo.jpg"""))


		.exec(http("clicBtnRevnEctsEtp_1")
			.get("""/stylesheets/ects_etp_search.xhtml"""))
		.pause(217 milliseconds)
		.exec(http("clicBtnRevnEctsEtp_2")
			.get("""/javax.faces.resource/jsf.js.xhtml?ln=javax.faces"""))
		.pause(22 milliseconds)
		.exec(http("clicBtnRevnEctsEtp_3")
			.get("""/javax.faces.resource/growl/assets/growl.css.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_4")
			.get("""/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces"""))
		.pause(14 milliseconds)
		.exec(http("clicBtnRevnEctsEtp_5")
			.get("""/javax.faces.resource/core/core.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_6")
			.get("""/javax.faces.resource/growl/growl.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_7")
			.get("""/javax.faces.resource/jquery/ui/jquery-ui.css.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_8")
			.get("""/javax.faces.resource/wijmo/wijgithmo.css.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_9")
			.get("""/javax.faces.resource/panel/panel.css.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_10")
			.get("""/javax.faces.resource/jquery/ui/jquery-ui.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_11")
			.get("""/javax.faces.resource/wijmo/wijmo.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_12")
			.get("""/javax.faces.resource/panel/panel.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_13")
			.get("""/javax.faces.resource/forms/forms.css.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_14")
			.get("""/javax.faces.resource/forms/forms.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_15")
			.get("""/javax.faces.resource/button/button.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_16")
			.get("""/javax.faces.resource/ajaxstatus/ajaxstatus.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_17")
			.get("""/javax.faces.resource/paginator/paginator.css.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_18")
			.get("""/javax.faces.resource/datatable/datatable.css.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_19")
			.get("""/javax.faces.resource/yui/utilities/utilities.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_20")
			.get("""/javax.faces.resource/paginator/paginator.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_21")
			.get("""/javax.faces.resource/datatable/datatable.js.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_22")
			.get("""/javax.faces.resource/themes/sam/theme.css.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_23")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/rennes1.css"""))
		.exec(http("clicBtnRevnEctsEtp_24")
			.get("""/media//style/ects.css""")
			.headers(headers))
		.pause(140 milliseconds)
		.exec(http("clicBtnRevnEctsEtp_25")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.reset.css"""))
		.exec(http("clicBtnRevnEctsEtp_26")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.layout.css"""))
		.exec(http("clicBtnRevnEctsEtp_27")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.text.css"""))
		.exec(http("clicBtnRevnEctsEtp_28")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/application.layout.css"""))
		.exec(http("clicBtnRevnEctsEtp_29")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.reset.css"""))
		.exec(http("clicBtnRevnEctsEtp_30")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.theme.css"""))
		.exec(http("clicBtnRevnEctsEtp_31")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.layout.css"""))
		.pause(35 milliseconds)
		.exec(http("clicBtnRevnEctsEtp_32")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/background_body.jpg"""))
		.exec(http("clicBtnRevnEctsEtp_33")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/logo-header.png"""))
		.exec(http("clicBtnRevnEctsEtp_34")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/background_logo.jpg"""))
		.exec(http("clicBtnRevnEctsEtp_35")
			.get("""/javax.faces.resource/themes/sam/images/ui-bg_flat_75_ffffff_40x100.png.xhtml?ln=primefaces"""))
		.exec(http("clicBtnRevnEctsEtp_36")
			.get("""/javax.faces.resource/themes/sam/images/sprite.png.xhtml?ln=primefaces"""))

		.exec(http("searchRevnEctsEtp_1")
			.get("""/stylesheets/ects_etp_search.xhtml"""))
		.pause(79 milliseconds)
		.exec(http("searchRevnEctsEtp_2")
			.get("""/javax.faces.resource/jsf.js.xhtml?ln=javax.faces"""))
		.pause(18 milliseconds)
		.exec(http("searchRevnEctsEtp_3")
			.get("""/javax.faces.resource/growl/assets/growl.css.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_4")
			.get("""/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces"""))
		.pause(14 milliseconds)
		.exec(http("searchRevnEctsEtp_5")
			.get("""/javax.faces.resource/core/core.js.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_6")
			.get("""/javax.faces.resource/growl/growl.js.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_7")
			.get("""/javax.faces.resource/jquery/ui/jquery-ui.css.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_8")
			.get("""/javax.faces.resource/wijmo/wijmo.css.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_9")
			.get("""/javax.faces.resource/panel/panel.css.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_10")
			.get("""/javax.faces.resource/jquery/ui/jquery-ui.js.xhtml?ln=primefaces"""))
		.pause(16 milliseconds)
		.exec(http("searchRevnEctsEtp_11")
			.get("""/javax.faces.resource/wijmo/wijmo.js.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_12")
			.get("""/javax.faces.resource/panel/panel.js.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_13")
			.get("""/javax.faces.resource/button/button.js.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_14")
			.get("""/javax.faces.resource/ajaxstatus/ajaxstatus.js.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_15")
			.get("""/javax.faces.resource/paginator/paginator.css.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_16")
			.get("""/javax.faces.resource/datatable/datatable.css.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_17")
			.get("""/javax.faces.resource/yui/utilities/utilities.js.xhtml?ln=primefaces"""))
		.pause(11 milliseconds)
		.exec(http("searchRevnEctsEtp_18")
			.get("""/javax.faces.resource/paginator/paginator.js.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_19")
			.get("""/javax.faces.resource/datatable/datatable.js.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_20")
			.get("""/javax.faces.resource/themes/sam/theme.css.xhtml?ln=primefaces"""))
		.exec(http("searchRevnEctsEtp_21")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/rennes1.css"""))
		.exec(http("searchRevnEctsEtp_22")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.fss.css"""))
		.exec(http("searchRevnEctsEtp_23")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.reset.css"""))
		.exec(http("searchRevnEctsEtp_24")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.layout.css"""))
		.exec(http("searchRevnEctsEtp_25")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.text.css"""))
		.exec(http("searchRevnEctsEtp_26")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/application.layout.css"""))
		.exec(http("searchRevnEctsEtp_27")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.reset.css"""))
		.exec(http("searchRevnEctsEtp_28")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.theme.css"""))
		.exec(http("searchRevnEctsEtp_29")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.layout.css"""))
		.exec(http("searchRevnEctsEtp_30")
			.get("""/media//style/ects.css""")
			.headers(headers))
		.pause(15 milliseconds)
		.exec(http("searchRevnEctsEtp_31")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/logo-header.png"""))
		.exec(http("searchRevnEctsEtp_32")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/background_logo.jpg"""))
    .exec(jsfGet("searchRevnEctsEtp_33_get", "/stylesheets/ects_etp_search.xhtml").headers(headers2))
    .pause(80 milliseconds)
    .exec(jsfPost("searchRevnEctsEtp_33_post", "/stylesheets/ects_etp_search.xhtml")
      .param("javax.faces.partial.ajax", "true")
      .param("javax.faces.source", "formEctsEtp:j_id_1h")
      .param("javax.faces.partial.execute", "@all")
      .param("javax.faces.partial.render", "formEctsEtp:vet")
      .param("editall", "editall")
      .param("formEctsEtp_SUBMIT", "1")
      .param("formEctsEtp:annee","2011")
      .param("formEctsEtp:codeEtape","DL0021")
      .param("formEctsEtp:filtre","")
      .param("formEctsEtp:j_id_1h","formEctsEtp:j_id_1h"))

		.exec(http("selectRevnEctsEtp_1")
			.get("""/stylesheets/ects_etp_inscrits.xhtml""")
			.headers(headers3))
		.pause(79 milliseconds)
		.exec(http("selectRevnEctsEtp_2")
			.get("""/javax.faces.resource/jsf.js.xhtml?ln=javax.faces"""))
		.pause(18 milliseconds)
		.exec(http("selectRevnEctsEtp_3")
			.get("""/javax.faces.resource/growl/assets/growl.css.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_4")
			.get("""/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces"""))
		.pause(14 milliseconds)
		.exec(http("selectRevnEctsEtp_5")
			.get("""/javax.faces.resource/core/core.js.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_6")
			.get("""/javax.faces.resource/growl/growl.js.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_7")
			.get("""/javax.faces.resource/jquery/ui/jquery-ui.css.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_8")
			.get("""/javax.faces.resource/wijmo/wijmo.css.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_9")
			.get("""/javax.faces.resource/panel/panel.css.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_10")
			.get("""/javax.faces.resource/jquery/ui/jquery-ui.js.xhtml?ln=primefaces"""))
		.pause(16 milliseconds)
		.exec(http("selectRevnEctsEtp_11")
			.get("""/javax.faces.resource/wijmo/wijmo.js.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_12")
			.get("""/javax.faces.resource/panel/panel.js.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_13")
			.get("""/javax.faces.resource/button/button.js.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_14")
			.get("""/javax.faces.resource/ajaxstatus/ajaxstatus.js.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_15")
			.get("""/javax.faces.resource/paginator/paginator.css.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_16")
			.get("""/javax.faces.resource/datatable/datatable.css.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_17")
			.get("""/javax.faces.resource/yui/utilities/utilities.js.xhtml?ln=primefaces"""))
		.pause(11 milliseconds)
		.exec(http("selectRevnEctsEtp_18")
			.get("""/javax.faces.resource/paginator/paginator.js.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_19")
			.get("""/javax.faces.resource/datatable/datatable.js.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_20")
			.get("""/javax.faces.resource/themes/sam/theme.css.xhtml?ln=primefaces"""))
		.exec(http("selectRevnEctsEtp_21")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/rennes1.css"""))
		.exec(http("selectRevnEctsEtp_22")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.fss.css"""))
		.exec(http("selectRevnEctsEtp_23")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.reset.css"""))
		.exec(http("selectRevnEctsEtp_24")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.layout.css"""))
		.exec(http("selectRevnEctsEtp_25")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.text.css"""))
		.exec(http("selectRevnEctsEtp_26")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/application.layout.css"""))
		.exec(http("selectRevnEctsEtp_27")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.reset.css"""))
		.exec(http("selectRevnEctsEtp_28")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.theme.css"""))
		.exec(http("selectRevnEctsEtp_29")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.layout.css"""))
		.exec(http("selectRevnEctsEtp_30")
			.get("""/media//style/ects.css""")
			.headers(headers))
		.pause(15 milliseconds)
		.exec(http("selectRevnEctsEtp_31")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/logo-header.png"""))
		.exec(http("selectRevnEctsEtp_32")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/background_logo.jpg"""))
		.pause(21)
    .exec(jsfGet("selectRevnEctsEtp_33_get", "/stylesheets/ects_etp_inscrits.xhtml").headers(headers2))
    .pause(80 milliseconds)
    .exec(jsfPost("selectRevnEctsEtp_33_post", "/stylesheets/ects_etp_inscrits.xhtml")
        .param("javax.faces.partial.ajax", "true")
        .param("javax.faces.source", "editall")
        .param("javax.faces.partial.execute", "@all")
        .param("javax.faces.partial.render", "growl")
        .param("editall", "editall")
        .param("formEctsEtp_SUBMIT", "1")
        .param("etudiants_selection",""))

		.exec(http("editRevnEctsEtp_1")
			.get("""/stylesheets/ects_etp_inscrits.xhtml"""))
		.pause(79 milliseconds)
		.exec(http("editRevnEctsEtp_2")
			.get("""/javax.faces.resource/jsf.js.xhtml?ln=javax.faces"""))
		.pause(18 milliseconds)
		.exec(http("editRevnEctsEtp_3")
			.get("""/javax.faces.resource/growl/assets/growl.css.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_4")
			.get("""/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces"""))
		.pause(14 milliseconds)
		.exec(http("editRevnEctsEtp_5")
			.get("""/javax.faces.resource/core/core.js.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_6")
			.get("""/javax.faces.resource/growl/growl.js.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_7")
			.get("""/javax.faces.resource/jquery/ui/jquery-ui.css.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_8")
			.get("""/javax.faces.resource/wijmo/wijmo.css.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_9")
			.get("""/javax.faces.resource/panel/panel.css.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_10")
			.get("""/javax.faces.resource/jquery/ui/jquery-ui.js.xhtml?ln=primefaces"""))
		.pause(16 milliseconds)
		.exec(http("editRevnEctsEtp_11")
			.get("""/javax.faces.resource/wijmo/wijmo.js.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_12")
			.get("""/javax.faces.resource/panel/panel.js.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_13")
			.get("""/javax.faces.resource/button/button.js.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_14")
			.get("""/javax.faces.resource/ajaxstatus/ajaxstatus.js.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_15")
			.get("""/javax.faces.resource/paginator/paginator.css.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_16")
			.get("""/javax.faces.resource/datatable/datatable.css.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_17")
			.get("""/javax.faces.resource/yui/utilities/utilities.js.xhtml?ln=primefaces"""))
		.pause(11 milliseconds)
		.exec(http("editRevnEctsEtp_18")
			.get("""/javax.faces.resource/paginator/paginator.js.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_19")
			.get("""/javax.faces.resource/datatable/datatable.js.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_20")
			.get("""/javax.faces.resource/themes/sam/theme.css.xhtml?ln=primefaces"""))
		.exec(http("editRevnEctsEtp_21")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/rennes1.css"""))
		.exec(http("editRevnEctsEtp_22")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.fss.css"""))
		.exec(http("editRevnEctsEtp_23")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.reset.css"""))
		.exec(http("editRevnEctsEtp_24")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.layout.css"""))
		.exec(http("editRevnEctsEtp_25")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/fluid/fluid.text.css"""))
		.exec(http("editRevnEctsEtp_26")
			.get("""http://styles.univ-rennes1.fr/skins/universality/common/css/application.layout.css"""))
		.exec(http("editRevnEctsEtp_27")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.reset.css"""))
		.exec(http("editRevnEctsEtp_28")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.theme.css"""))
		.exec(http("editRevnEctsEtp_29")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/application.layout.css"""))
		.exec(http("editRevnEctsEtp_30")
			.get("""/media//style/ects.css""")
			.headers(headers))
		.pause(15 milliseconds)
		.exec(http("editRevnEctsEtp_31")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/logo-header.png"""))
		.exec(http("editRevnEctsEtp_32")
			.get("""http://styles.univ-rennes1.fr/skins/universality/rennes1/images/background_logo.jpg"""))
		.pause(21)
    .exec(jsfGet("editRevnEctsEtp_33_get", "/stylesheets/ects_etp_inscrits.xhtml").headers(headers2))
    .pause(80 milliseconds)
    .exec(jsfPost("editRevnEctsEtp_33_post", "/stylesheets/ects_etp_inscrits.xhtml")
        .param("javax.faces.partial.ajax", "true")
        .param("javax.faces.source", "editall")
        .param("javax.faces.partial.execute", "@all")
        .param("javax.faces.partial.render", "growl")
        .param("editall", "editall")
        .param("formEctsEtp_SUBMIT", "1")
        .param("etudiants_selection",""))
		.pause(257)
		.exec(http("editRevnEctsEtp_34")
			.get("""/download?downloadId=1397812743034"""))

	setUp(echelleNotEctsEtp.inject(atOnce(10 user))).protocols(httpProtocol)
}
